- name: Windows Feature
  hosts: newcon_core
  vars_files:
    - vars/variaveis.yaml    
  gather_facts: false
  tasks:
    ## Obter a data e hora atual
    - name: Obter data e hora atual
      win_shell: Get-Date -Format "yyyyMMdd_HHmmss"
      register: data_hora

    ## Remover caracteres do final da string data e hora
    - name: Remove caracteres de controle no final da string Date
      set_fact:
        data_hora_atual: "{{ data_hora.stdout | regex_replace('[\\r\\n\\t]+','') }}"

    ####################################################
    ## Valida se tem binarios do Newcon Core
    ####################################################   
    - name: Valida se tem binarios do Newcon Core
      win_find:
        paths: '{{ dir_newcon_deploy }}\Releases\Bin_Newcon_Core\'
        patterns: "*.*"
      register: exists_bin_core

    ## Faz o backup do newcon core (pacote atual)
    - name: Criar arquivo ZIP Newcon Core
      community.windows.win_zip:
        src: C:\Newcon\Bin_Newcon_Core\*
        dest: '{{ dir_newcon_deploy }}\Backups\newcon_core_{{ data_hora_atual }}.zip'
      when: exists_bin_core.matched > 0   
 
    ## Atualiza o pacote do newcon core (pacote novo)
    - name: Copiar binarios para diretorio do Newcon Core
      ansible.windows.win_copy:
        src: '{{ dir_newcon_deploy }}\Releases\Bin_Newcon_Core\'
        dest: C:\Newcon\Bin_Newcon_Core\
        remote_src: true            
      when: exists_bin_core.matched > 0   

