- name: Windows Feature
  hosts: sch_conins
  vars_files:
    - vars/variaveis.yaml    
  gather_facts: false
  tasks:
    ## Obter a data e hora atual
    - name: Obter data e hora atual
      win_shell: Get-Date -Format "yyyyMMdd_HHmmss"
      register: data_hora

    ## Remover caracteres do final da string data e hora
    - name: Remove caracteres de controle no final da string Date
      set_fact:
        data_hora_atual: "{{ data_hora.stdout | regex_replace('[\\r\\n\\t]+','') }}"

    ####################################################
    ## Valida se tem binarios do Schedulers e Conins
    ####################################################       
    - name: Tem binarios do Schedulers e Conins
      win_find:
        paths: '{{ dir_newcon_deploy }}\Releases\Bin_Sch_Conins\'
        patterns: "*.*"
      register: exists_bin_sch

    ## Faz o backup dos binários do sch e conins
    - name: Criar arquivo ZIP Sch Conins
      community.windows.win_zip:
        src: C:\Newcon\Bin_Sch_Conins\*
        dest: '{{ dir_newcon_deploy }}\Backups\sch_conins_{{ data_hora_atual }}.zip'
      when: exists_bin_sch.matched > 0   

    ## Atualiza o pacote do sch e conins
    - name: Copiar binarios para diretorio sch_conins
      ansible.windows.win_copy:
        src: '{{ dir_newcon_deploy }}\Releases\Bin_Sch_Conins\'
        dest: C:\Newcon\Bin_Sch_Conins\
        remote_src: true            
      when: exists_bin_sch.matched > 0

