- name: Windows Feature
  hosts: win
  gather_facts: true
  tasks:
    ####################################################
    ## Valida se tem binarios do Schedulers e Conins
    ####################################################       
    - name: Tem binarios do Schedulers e Conins
      win_find:
        paths: C:\Newcon_Versao\Releases\Bin_Sch_Conins\
        patterns: "*.*"
      register: exists_bin_sch

    ## Faz o backup dos binários do sch e conins
    - name: Criar arquivo ZIP Sch Conins
      community.windows.win_zip:
        src: C:\Newcon\Bin_Sch_Conins\*
        dest: 'C:\Newcon\Backups\sch_conins_{{ data_hora_atual }}.zip'
      when: exists_bin_sch.matched > 0   

    ## Atualiza o pacote do sch e conins
    - name: Copiar binarios para diretorio sch_conins
      ansible.windows.win_copy:
        src: C:\Newcon_Versao\Releases\Bin_Sch_Conins\
        dest: C:\Newcon\Bin_Sch_Conins\
        remote_src: true            
      when: exists_bin_sch.matched > 0

