- name: Windows Feature
  hosts: web
  vars_files:
    - vars/variaveis.yaml    
  gather_facts: false
  tasks:
    ## Obter a data e hora atual
    - name: Obter data e hora atual
      win_shell: Get-Date -Format "yyyyMMdd_HHmmss"
      register: data_hora

    ## Remover caracteres do final da string data e hora
    - name: Remove caracteres de controle no final da string Date
      set_fact:
        data_hora_atual: "{{ data_hora.stdout | regex_replace('[\\r\\n\\t]+','') }}"

    ####################################################
    ## Valida se tem pacotes web
    ####################################################        
    - name: Valida se tem pacotes web para atualizar
      win_find:
        paths: '{{ dir_newcon_deploy }}\Releases\Web\'
        patterns: "Intranet_Newcon.Web.Api*.zip"
      register: exists_newcon_web_api
  
    ## Parar o application pool - Intranet_Newcon.Web.Api
    - name: Parar Application Pool
      win_iis_webapppool:
        name: newcon.web.api
        state: stopped
      when: exists_newcon_web_api.matched > 0      

    ## Faz o backup Intranet_Newcon.Web.Api (pacote atual)
    - name: Criar arquivo ZIP Intranet_Newcon.Web.Api
      community.windows.win_zip:
        src: '{{ dir_newcon_web }}\Newcon.Web.Api\*'
        dest: '{{ dir_newcon_deploy }}\Backups\Intranet_Newcon.Web.Api_{{ data_hora_atual }}.zip'
      when: exists_newcon_web_api.matched > 0           

    ## Atualiza pacote web - Intranet_Newcon.Web.Api
    #### ATENÇÃO!! Pre-req: ter instalado o 7zip no servidor de destino + o 7zip configurado no path
    - name: Descompactar pacote
      win_shell: |
        7z x {{ dir_newcon_deploy }}\Releases\Web\Intranet_Newcon.Web.Api_004_030.zip -o{{ dir_newcon_web }}\ -aoa '-xr!web.config' '-xr!appsettings.json' '-xr!nlog.json' '-xr!log.config'
      when: exists_newcon_web_api.matched > 0

    ## Iniciar o application pool - Intranet_Newcon.Web.Api
    - name: Iniciar Application Pool
      win_iis_webapppool:
        name: newcon.web.api
        state: started
      when: exists_newcon_web_api.matched > 0

    ## Verifica se a o Newcon Web subiu OK
    - name: Verificar status da URL
      ansible.windows.win_uri:
        url: "http://localhost/newcon.web/"
        return_content: no
      register: response

    ## Exibe mensagem se estiver OK
    - name: Exibir mensagem com base no status da URL
      debug:
        msg: "A URL está retornando 200 OK"
      when: response.status_code == 200     
