---
- name: Windows Feature
  hosts: win
  gather_facts: true
  tasks:
     - name: Executar script PowerShell
       win_shell: |
         $resultado = c:\Newcon_Versao\atualiza_script.ps1
       register: script_output    

     - name: Valida a saida da task anterior
       fail:
       when: script_output.stdout == 'Processo finalizado sem sucesso'    
