---
- name: Windows Feature
  hosts: win
  gather_facts: true
  tasks:
    - name: Criar estrutura de diretorios
      ansible.windows.win_file:
        path: C:\NewDeploy\Pacotes
        state: directory      
      when: 0 > 1

    - name: Download do pacote da versao
      ansible.windows.win_get_url:
        url: https://www4.newconsoftware.com.br/teste/SCRIPT_004_030_SEQ_000003.zip
        dest: C:\NewDeploy\Pacotes\SCRIPT_004_030_SEQ_000003.zip
      when: 0 > 1

    - name: Descompactar pacote
      community.windows.win_unzip:
        src: C:\NewDeploy\Pacotes\SCRIPT_004_030_SEQ_000003.zip
        dest: C:\Newcon_Versao\Releases\
      when: 0 > 1

    - name: Valida se tem Script de BD
      win_find:
        paths: C:\Newcon_Versao\Releases\
        patterns: "*.ver"
      register: exists_script_db

    - name: Atualizar Script de BD
      win_shell: |
        $resultado = c:\Newcon_Versao\atualiza_script.ps1
      register: script_process    
      when: exists_script_db.matched > 0

    - name: Valida se o script de BD foi atualizado com sucesso
      fail:
      when: 0 > 1 #script_process.stdout == 'Processo finalizado sem sucesso.\n'      

    - name: Tem binarios do Newcon Core
      win_find:
        paths: C:\Newcon_Versao\Releases\Bin_Newcon_Core\
        patterns: "*.*"
      register: exists_bin_core

    - name: Obter data e hora atual
      win_shell: Get-Date -Format "yyyyMMdd_HHmmss"
      register: data_hora_atual

    - name: Criar arquivo ZIP
      community.windows.win_zip:
        src: C:\Newcon\Bin_Newcon_Core\*
        dest: C:\Newcon\Backups\arquivo_{{ data_hora_atual.stdout | regex_replace('[\\r\\n\\t]+','') }}.zip
     # community.windows.win_zip:    
     # win_command: powershell.exe -Command "Compress-Archive -Path 'C:\Newcon\Bin_Newcon_Core\' -DestinationPath 'C:\Newcon\Backups\arquivo_{{ data_hora_atual.stdout }}.zip'"

    - name: Copiar binarios para diretorio Core
      ansible.windows.win_copy:
        src: C:\Newcon_Versao\Releases\Bin_Newcon_Core\
        dest: C:\Newcon\Bin_Newcon_Core\
        backup: yes
        remote_src: true            
      when: exists_bin_core.matched > 0   

    - name: Tem binarios do Schedulers e Conins
      win_find:
        paths: C:\Newcon_Versao\Releases\Bin_Sch_Conins\
        patterns: "*.*"
      register: exists_bin_sch

    - name: Copiar binarios para diretorio sch_conins
      ansible.windows.win_copy:
        src: C:\Newcon_Versao\Releases\Bin_Sch_Conins\
        dest: C:\Newcon\Bin_Sch_Conins\
        remote_src: true            
      when: exists_bin_sch.matched > 0         
       

