---
- name: Windows Feature
  hosts: win
  gather_facts: true
  tasks:
     - name: Executar script PowerShell
       win_shell: |
         $resultado = c:\Newcon_Versao\atualiza_script.ps1
       register: script_output    
     - meta: 
         end_play  
