---
- name: Windows Feature
  hosts: win
  gather_facts: true
  tasks:
     - name: Executar script PowerShell
       win_command: powershell.exe -ExecutionPolicy ByPass -File C:\Newcon_Versao\atualiza_script.ps1