- name: Windows Feature
  hosts: win
  gather_facts: true
  tasks:
    - name: Run ipconfig and return IP address information.
      raw: ipconfig
      register: ipconfig
    #- debug: var=ipconfig

    - name: Install IIS Web-Server with sub features and management tools
      ansible.windows.win_feature:
        name: Web-Server
        state: present
        include_sub_features: true
        include_management_tools: true
      register: win_feature